# Site settings
title: Data and the Third Sector
description: "A blog about data science, with a focus on charities, voluntary and community organisations"
url: "http://www.bsuthersan.github.io/blog"
author:
  name: Bridget Suthersan
  email: "bridget.suthersan@gmail.com"
  url: "https://bsuthersan.github.io"

# Build settings
baseurl: /blog
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
